# Generated by Django 4.0.5 on 2022-06-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile1', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
