# Generated by Django 4.0.5 on 2022-06-17 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('drive_type', models.CharField(choices=[('RWD', 'RWD'), ('FWD', 'FWD'), ('4WD', '4WD'), ('AWD', 'AWD')], max_length=20, verbose_name='Тип привода')),
                ('transmission', models.CharField(choices=[('механическая', 'механическая'), ('автоматическая', 'автоматическая'), ('роботизированная', 'роботизированная'), ('бесступенчатая', 'бесступенчатая')], max_length=100, verbose_name='Каробка передач')),
                ('сondition', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=20, verbose_name='Состояние')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('fuel_type', models.CharField(choices=[('бензин', 'бензин'), ('дизель', 'дизель'), ('биодизель', 'биодизель'), ('биоэтанол', 'биоэтанол'), ('керосин', 'керосин'), ('газ', 'газ')], max_length=50, verbose_name='Тип топлива')),
                ('engine_size', models.FloatField(verbose_name='Обьём мотора')),
                ('doors', models.IntegerField(verbose_name='Двери')),
                ('cylinders', models.IntegerField(verbose_name='Цилиндры')),
                ('vin', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='auto/', verbose_name='Фото')),
                ('prise', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Ссылка(ютуб)')),
            ],
            options={
                'verbose_name': 'Автомабиль',
                'verbose_name_plural': 'Автомабили',
            },
        ),
        migrations.CreateModel(
            name='AutoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField(verbose_name='отзыв')),
                ('comfort', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=11, verbose_name='комфорт')),
                ('performance', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=11, verbose_name='представление')),
                ('exterior_styling', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=11, verbose_name='внешний вид')),
                ('interior_design', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=11, verbose_name='дизайн интерьера')),
                ('value_for_the_money', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=11, verbose_name='ценa и качество')),
                ('reliability', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=11, verbose_name='надежность')),
                ('time_c', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.auto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auto_image_slider/')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.auto')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Auto_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.auto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.make', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='auto',
            name='type_auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.autotype'),
        ),
        migrations.AddField(
            model_name='auto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
