# Generated by Django 4.0.5 on 2022-06-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_autotype_options_autotype_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='engine_size',
            field=models.IntegerField(verbose_name='Обьём мотора'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='type_auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.autotype', verbose_name='Tип'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='сondition',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Б/У', 'Б/У')], max_length=20, verbose_name='Состояние'),
        ),
    ]
