# Generated by Django 4.0.5 on 2022-06-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_auto_engine_size_alter_auto_type_auto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='make',
            old_name='name',
            new_name='title',
        ),
    ]
