# Generated by Django 4.0.5 on 2022-06-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_name_make_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='engine_size',
            field=models.FloatField(verbose_name='Обьём мотора'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='comfort',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='комфорт'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='exterior_styling',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='внешний вид'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='interior_design',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='дизайн интерьера'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='performance',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='представление'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reliability',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='надежность'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='value_for_the_money',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='ценa и качество'),
        ),
    ]
