# Generated by Django 4.0.5 on 2022-06-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_auto_engine_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='engine_size',
            field=models.FloatField(verbose_name='Обьём мотора'),
        ),
    ]
