# Generated by Django 4.0.5 on 2022-06-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_auto_engine_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='engine_size',
            field=models.IntegerField(verbose_name='Обьём мотора'),
        ),
    ]
