# Generated by Django 4.0.5 on 2022-06-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
