# Generated by Django 4.0.5 on 2022-06-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_delete_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'ordering': ['-id'], 'verbose_name': 'Автомабиль', 'verbose_name_plural': 'Автомабили'},
        ),
    ]
