# Generated by Django 4.0.5 on 2022-06-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_auto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='video_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка(ютуб)'),
        ),
    ]
