# Generated by Django 4.0.5 on 2022-06-27 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_auto_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reviews',
            new_name='text',
        ),
        migrations.AddField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.reviews'),
        ),
    ]
