# Generated by Django 4.0.5 on 2022-06-29 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0014_remove_reviews_parent_otvety'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otvety',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AddField(
            model_name='otvety',
            name='parent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.otvety', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='otvety',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.reviews', verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='otvety',
            name='text',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='otvety',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
